<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\Version.props" />
	<Import Project="..\..\PackNuget.props" />
	<PropertyGroup>
		<NoWarn>$(NoWarn);Rpc0004</NoWarn>
  <TargetFrameworks>net8.0;$(OtherTargetFrameworks);</TargetFrameworks>
		
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
		<PackageReference Include="Riok.Mapperly" Version="4.3.0" ExcludeAssets="runtime" PrivateAssets="all">
		  <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Rougamo.Fody" Version="5.0.2" />
		<PackageReference Include="TouchSocket.Dmtp" Version="$(TSVersion)" />
		<!--<PackageReference Include="TouchSocket.WebApi.Swagger" Version="$(TSVersion)" />-->
		<PackageReference Include="TouchSocket.WebApi" Version="$(TSVersion)" />
		<PackageReference Include="ThingsGateway.Authentication" Version="$(AuthenticationVersion)" />
		<!--<ProjectReference Include="..\..\PluginPro\ThingsGateway.Authentication\ThingsGateway.Authentication.csproj" />-->

	</ItemGroup>

	<ItemGroup>
		<Content Remove="SeedData\Gateway\*.json" />
		<Content Include="SeedData\Gateway\*.json" Pack="true" PackagePath="\Content\SeedData\Gateway\">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>

		<Content Remove="SeedData\Management\*.json" />
		<Content Include="SeedData\Management\*.json" Pack="true" PackagePath="\Content\SeedData\Management\">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>

		<Content Remove="SeedData\RulesEngine\*.json" />
		<Content Include="SeedData\RulesEngine\*.json" Pack="true" PackagePath="\Content\SeedData\RulesEngine\">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>

	</ItemGroup>

	<ItemGroup>
		<Content Remove="Locales\*.json" />
		<EmbeddedResource Include="Locales\*.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\..\Admin\ThingsGateway.Admin.Application\ThingsGateway.Admin.Application.csproj" />
		<ProjectReference Include="..\..\..\..\Industrial.Security\src\Industrial.Security.Abstractions\Industrial.Security.Abstractions.csproj" />
		<ProjectReference Include="..\..\Foundation\ThingsGateway.CSScript\ThingsGateway.CSScript.csproj" />
		<ProjectReference Include="..\..\Foundation\ThingsGateway.Foundation\ThingsGateway.Foundation.csproj" />
		<ProjectReference Include="..\ThingsGateway.Blazor.Diagrams.Core\ThingsGateway.Blazor.Diagrams.Core.csproj" />
	</ItemGroup>


	<ItemGroup Condition=" '$(TargetFramework)' != 'net10.0' ">
		<PackageReference Include="System.Linq.Async" Version="6.0.3" />
	</ItemGroup>
	
</Project>
