<Project Sdk="Microsoft.NET.Sdk.Razor">
	<Import Project="..\..\Version.props" />
	<Import Project="..\..\PackNuget.props" />
	<PropertyGroup>
		<TargetFrameworks>net8.0;$(OtherTargetFrameworks);</TargetFrameworks>
		<OutputPath>bin\$(Configuration)</OutputPath>
		<IntermediateOutputPath>obj\$(Configuration)\</IntermediateOutputPath>

	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Foundation\ThingsGateway.Foundation.Razor\ThingsGateway.Foundation.Razor.csproj">
		</ProjectReference>
		<ProjectReference Include="..\..\Gateway\ThingsGateway.Gateway.Razor\ThingsGateway.Gateway.Razor.csproj">
		</ProjectReference>

		
	</ItemGroup>


	<ItemGroup>
		<Content Remove="Locales\*.json" />
		<EmbeddedResource Include="Locales\*.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>
	
	
	<ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
		<PackageReference Include="MQTTnet.AspNetCore" Version="4.3.7.1207" GeneratePathProperty="true">
			<PrivateAssets>contentFiles;build;buildMultitargeting;buildTransitive;analyzers;</PrivateAssets>
		</PackageReference>
		<PackageReference Include="MQTTnet" Version="4.3.7.1207" GeneratePathProperty="true">
			<PrivateAssets>contentFiles;build;buildMultitargeting;buildTransitive;analyzers;</PrivateAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup Condition=" '$(TargetFramework)' != 'net6.0' ">
		<PackageReference Include="MQTTnet.Server" Version="5.1.0.1559" GeneratePathProperty="true">
			<PrivateAssets>contentFiles;build;buildMultitargeting;buildTransitive;analyzers;</PrivateAssets>
		</PackageReference>
		<PackageReference Include="MQTTnet.AspNetCore" Version="5.1.0.1559" GeneratePathProperty="true">
			<PrivateAssets>contentFiles;build;buildMultitargeting;buildTransitive;analyzers;</PrivateAssets>
		</PackageReference>
		<PackageReference Include="MQTTnet" Version="5.1.0.1559" GeneratePathProperty="true">
			<PrivateAssets>contentFiles;build;buildMultitargeting;buildTransitive;analyzers;</PrivateAssets>
		</PackageReference>
	</ItemGroup>

</Project>


 
