<Project>

	<PropertyGroup>
		<PluginVersion>10.12.36</PluginVersion>
		<ProPluginVersion>10.12.36</ProPluginVersion>
		<DefaultVersion>10.12.36</DefaultVersion>
		<AuthenticationVersion>10.11.8</AuthenticationVersion>
		<SourceGeneratorVersion>10.11.8</SourceGeneratorVersion>
		<NET8Version>8.0.22</NET8Version>
		<NET10Version>10.0.0</NET10Version>
		<SatelliteResourceLanguages>zh-Hans;en-US</SatelliteResourceLanguages>
		<IsTrimmable>false</IsTrimmable>
		<ManagementProPluginVersion>10.11.87</ManagementProPluginVersion>
		<ManagementPluginVersion>10.11.87</ManagementPluginVersion>
		<TSVersion>4.0.0-rc.46</TSVersion>
		
		
	</PropertyGroup>


	<PropertyGroup Condition="'$(VisualStudioVersion)' >= '18.0' OR $([MSBuild]::VersionGreaterThanOrEquals('$(MSBuildVersion)','18.0'))">
		<OtherTargetFrameworks>net10.0</OtherTargetFrameworks>
	</PropertyGroup>

	<PropertyGroup>
		<RestoreEnablePackagePruning Condition="'$(TargetFramework)' == 'net462' "> false</RestoreEnablePackagePruning>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(TargetFramework)' != 'net8.0' ">
		<PluginTargetFramework>net10.0</PluginTargetFramework>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
		<PluginTargetFramework>net8.0</PluginTargetFramework>
	</PropertyGroup>
	
	<PropertyGroup>

		<AnalysisModeDesign>None</AnalysisModeDesign>
		<AnalysisModeDocumentation>All</AnalysisModeDocumentation>
		<AnalysisModeGlobalization>None</AnalysisModeGlobalization>
		<AnalysisModeInteroperability>All</AnalysisModeInteroperability>
		<AnalysisModeMaintainability>All</AnalysisModeMaintainability>
		<AnalysisModeNaming>None</AnalysisModeNaming>
		<AnalysisModePerformance>All</AnalysisModePerformance>
		<AnalysisModeSingleFile>All</AnalysisModeSingleFile>
		<AnalysisModeReliability>All</AnalysisModeReliability>
		<AnalysisModeSecurity>All</AnalysisModeSecurity>
		<AnalysisModeUsage>None</AnalysisModeUsage>
		<AnalysisModeStyle>None</AnalysisModeStyle>

		<NoWarn>
			NU1510;NU1605;SYSLIB5007;CS8603;CS8618;CS1591;CS8625;CS8602;CS8604;CS8600;CS8601;CS8714;CS8619;CS8629;CS8765;CS8634;CS8621;CS8767;CS8633;CS8620;CS8610;CS8631;CS8605;CS8622;CS8613;NU5100;NU5104;NU1903;NU1902;CA1863;CA1812;CA1805;CA1515;CA1508;CA1819;CA1852;CA5394;CA1822;CA1815;CA1813;CA2000;CA5358;CA5384;CA5400;CA5401;CA1814;CA1835;CA5392;CA5350;CA2100;CA1848;CA1810;CA1513;CA5351;CA1510;CA1512;CA1823;RCS1102;RCS1194;NETSDK1206

		</NoWarn>
		<TargetFrameworks>net8.0;$(OtherTargetFrameworks);</TargetFrameworks>
		<LangVersion>13.0</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Authors>Diego</Authors>
		<Company>Diego</Company>
		<Product>Diego</Product>
		<Copyright>版权所有 © 2023-present Diego</Copyright>
		<RepositoryUrl>https://gitee.com/diego2098/ThingsGateway</RepositoryUrl>
		<RepositoryType>Gitee</RepositoryType>
		<GenerateResxSourceIncludeDefaultValues>true</GenerateResxSourceIncludeDefaultValues>
	</PropertyGroup>

	<ItemGroup>
		<None Include="$(MSBuildThisFileDirectory)Directory.Build.props" Pack="true" PackagePath="\" />
	</ItemGroup>

	<PropertyGroup>
		<DebugSymbols>True</DebugSymbols>
		<DebugType>Embedded</DebugType>
		<EmbedAllSources>True</EmbedAllSources>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Roslynator.Analyzers" Version="4.14.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>



	<Target Name="EnsureLocalNugetFolderExists" BeforeTargets="CollectPackageReferences">
		<MakeDir Directories="$(SolutionDir)..\..\nupkgs" />
	</Target>


	<PropertyGroup Condition=" '$(TargetFramework)' == 'net10.0' ">
		<!--<enablepreviewfeatures>true</enablepreviewfeatures>
		<features>$(features);runtime-async=on</features>
		<langversion>preview</langversion>
		<DOTNET_RuntimeAsync>1</DOTNET_RuntimeAsync>-->
	</PropertyGroup>
	
</Project>
